### ISSUE TITLE
End User License Agreement

### ISSUE THREAD

**Issue by kosssi** [bfren/docker-ocis#31]
Hello @bfren 

ownCloud Infinite Scale is Open Source with [Apache 2.0](https://github.com/owncloud/ocis/blob/master/LICENSE) license, but all stable versions build by ownCloud are subject to the [End User Licencse Agreement](https://owncloud.com/license-owncloud-infinite-scale/). You can read discussions on [this commit](https://github.com/owncloud/ocis/commit/fd8f2776733d030818fa5092298de05f08f9efb9).

The limitation (3a) is: You must not install and use ownCloud Infinite Scale for Commercial Use.

[Another discution](https://github.com/owncloud/ocis/issues/6570#issuecomment-1628636974) is interesting to read :

> Note that the EULA is only valid for builds provided by ownCloud GmbH, and allows even commercial use widely.

[You download the binary from owncloud](https://github.com/bfren/docker-ocis/blob/main/Dockerfile#L21) in your Docker image, you are therefore subject to EULA, it would be better to display it clearly in your README or change the way you build the image.

I have the impression that there is no Docker image entirely independent of ownCloud builds, maybe a great project ^^

**Comment by bfren** [comment]
That's an excellent point, I'm minded to simply remove the image in that case and use theirs.  Thank you for pointing that out!
